---
title: "Introduction"
author: "Gusti Adli Anshari"
date: "8/2/2020"
output: html_document
---

## Preparing the Environment
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(scipen= 999999)
options("getSymbols.warning4.0"=FALSE)
packs <- c('dplyr', 'quantmod', 'devtools', 'forecast', 'readxl')
packs_to_install <- packs[!(packs %in% installed.packages())]
if(length(packs_to_install) > 0){
    install.packages(packs_to_install)
}
if(!'highcharter' %in% installed.packages()){
  install.packages("XML", repos = "http://www.omegahat.net/R")
  install.packages('rlist')
  devtools::install_github("jbkunst/highcharter")
}
if(!'modeltime' %in% installed.packages()){
  devtools::install_github("business-science/modeltime")
}
```


```{r}
library(highcharter)
library(forecast)
library(dplyr)
library(quantmod)
library(modeltime)
```


```{r, warning= FALSE}
tickers <- readxl::read_xlsx('data_input/Yahoo Ticker Symbols - September 2017.xlsx', sheet = 'Stock', col_names = FALSE)[-(1:4), c(1,2)]
colnames(tickers) <- c('ticker_', 'name')
ticker <- 'BBCA.JK'
name <- tickers %>% filter(ticker_ == ticker) %>% pull(name) %>% toString()
ticker
name
df <- getSymbols(ticker, auto.assign= FALSE)
'----- head'
head(df)
'----- tail'
tail(df)
'----- summary'
summary(df)
```

We have some missing values, lets check where are they.
```{r}
df %>% subset(is.na(BBCA.JK.Open))
```

Since this is time series data, I will use time series interpolation to fill the missing values
```{r}
impute_ts <- function(x){
  x <- ts(x, 1, length(x))
  na.interp(x)
}
# function testing
df[, 1] %>% impute_ts() %>% summary()
df[, 2] %>% impute_ts() %>% summary()
```

```{r}
impute_df <- function(df){
  for (i in 1:length(df[1,])){
    df[, i] <- df[, i] %>% impute_ts()
  }
  df
}

df %>% impute_df() %>% summary()
```

Applying the imputation function
```{r}
df <- df %>% impute_df()
```

```{r}
tail(RSI(df[ ,4]))
```

```{r}
tail(BBands(df[, 2:4]))
```
```{r}
tail(MACD(df[, 4]))
```

```{r}
short_ma_ser <- SMA(df[, 4], 20)
long_ma_ser <- SMA(df[, 4], 100)

hcPlotStock <- function(df, ticker_name, ticker, show_ma = TRUE, show_bbands = FALSE, show_volume = TRUE, show_macd = FALSE, show_rsi = TRUE, short_ma = short_ma_ser, long_ma = long_ma_ser){
  # colnames(df) <- c('Open', 'High', 'Low', 'Close', 'Volume', 'Adjusted')
  n_axis <- show_volume + show_macd + show_rsi + 1
  height_axis <- c(2, seq(1, 1, length.out = n_axis - 1))
  y_macd <- 1 + show_volume
  y_rsi <- 1 + show_volume + show_macd
  hcChart <- highchart(type = 'stock') %>% 
    # create axis
    hc_yAxis_multiples(create_yaxis(n_axis, height = height_axis, turnopposite = TRUE)) %>% 
    # decimals setting
    hc_tooltip(valueDecimals = 2)
  
  if(show_volume){
    hcChart <- hcChart %>% 
      ## Add volume
      hc_add_series(df[, 5], color = "orange", yAxis = 1, name = "Volume", type = "column", showInLegend = FALSE)
  }
  
  if(show_macd){
    # calculate MACD
    macd <- MACD(df[, 4], 12, 26, 9) 
    macd$diff <- macd$macd - macd$signal
    diff.high <- ifelse(macd$diff > 0, macd$diff, 0)
    diff.low <- ifelse(macd$diff < 0, macd$diff, 0)
    hcChart <- hcChart %>% 
      # set Bar Chart Stacking Option
      hc_plotOptions(column = list(stacking = "normal")) %>% 
      ## Add MACD
      hc_add_series(diff.high, yAxis = y_macd, name = 'MACD diff', type = 'column', color = 'green', showInLegend = FALSE, enableMouseTracking = FALSE, stack = 'diff') %>% 
      hc_add_series(diff.low, yAxis = y_macd, name = 'MACD diff', type = 'column', color = 'red', showInLegend = FALSE, enableMouseTracking = FALSE, stack = 'diff') %>% 
      hc_add_series(macd$macd, yAxis = y_macd, name = 'MACD', color = 'blue', showInLegend = FALSE) %>% 
      hc_add_series(macd$signal, yAxis = y_macd, name = 'Signal Line', color = 'orange', showInLegend = FALSE)
  }
  
  if(show_rsi){
    hcChart <- hcChart %>%
      ## RSI
      hc_add_series(RSI(df[, 4]), yAxis = y_rsi, name = "Relative Stregth Index", color = hex_to_rgba("green", 0.7), showInLegend = FALSE) %>%
      hc_add_series(xts(rep(70, NROW(df)), index(df)), color = hex_to_rgba("red", 0.7), yAxis = y_rsi, name = "Sell level", enableMouseTracking = FALSE, dashStyle = 'LongDash') %>%
      hc_add_series(xts(rep(30, NROW(df)), index(df)), color = hex_to_rgba("blue", 0.7), yAxis = y_rsi, name = "Buy level", enableMouseTracking = FALSE, dashStyle = 'LongDash') %>% 
      # decimals setting
      hc_tooltip(valueDecimals = 2)
  }  
  
  
  if(show_ma){
    hcChart <- hcChart %>%
      ## Moving Averages
      hc_add_series(short_ma, yAxis = 0, name = 'Short Moving Average', color = 'seagreen', enableMouseTracking = FALSE) %>%
      hc_add_series(long_ma, yAxis = 0, name = 'Long Moving Average', color = 'skyblue', enableMouseTracking = FALSE)
  }
  
  
  if(show_bbands){
    # calculate Bollinger bands position
    bbands <- BBands(df[,2:4])
    hcChart <- hcChart %>%
      ## Add Bollinger Bands
      hc_add_series(bbands[, 'up'], yAxis = 0, name = 'Bollinger Bands', color = '#ccc', enableMouseTracking = FALSE, showInLegend = FALSE) %>%
      hc_add_series(bbands[, 'dn'], yAxis = 0, name = 'Bollinger Bands', color = '#ccc', enableMouseTracking = FALSE) %>% 
      hc_add_series(bbands[, 'mavg'], yAxis = 0, name = 'Moving Average (20)', color = '#E377C2', enableMouseTracking = FALSE)
  }
  
  
  hcChart %>%
    # add title
    hc_title(text = paste(ticker, ticker_name, sep = ' - '), align = 'left', x = 30) %>% 
    # add series
    ## candlechart
    hc_add_series(df, yAxis = 0, name = ticker, showInLegend = FALSE) %>%
    # add legend
    hc_legend(enabled = TRUE, align = 'center') %>% 
    # set theme
    hc_add_theme(hc_theme_db())
}


hcPlotStock(df, name, ticker)
```

```{r}
hcPlotStock(df, name, ticker, FALSE, TRUE, TRUE, TRUE, TRUE)
```

```{r}
hcPlotStock(df, name, ticker, TRUE, FALSE, FALSE, TRUE, FALSE)
```

```{r}
hcPlotStock(df, name, ticker, FALSE, FALSE, FALSE, TRUE, TRUE)
```




